#-------------------------------
# General Site Settings
title: fresco design works
# logo: '/images/logo-fresco.png'
description: Content creators for businesses.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://frescodesignworks.github.io" # the base hostname & protocol for your site, e.g. http://example.com
blog-theme: light # By default, Atega theme uses a 'light' color scheme, to change the color scheme to dark use 'dark' value (_includes/color-scheme)


#-------------------------------
# Author Settings
author:
  name: Simone Precicchiani
  image: '/images/me.jpg'


#-------------------------------
# Hero Settings
hero:
  hero__title: Hi, I'm <span class="hero__name">Simone Precicchiani</span>.
  hero__job: Graphic Designer
  hero__description: Creative and pragmatic problem solver.
  hero__button__text: Learn more
  hero__button__link: '/about'
  hero__image: '/images/01.jpg'


#-------------------------------
# Newsletter (_includes/footer-widgets/widget-subscribe.html)
mailchimp__title: Subscribe to new posts # Add your Title
mailchimp__text: Subscribe to our newsletter and we’ll send you the emails of latest posts. # Add your description.
mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
mailchimp__button__text: Subscribe # Add your button text


#-------------------------------
# Contact Settings
contact:
  email: simone.precicchiani@gmail.com # Add your email for contant form
  description: If you are interested to talk, just shoot me a message

# NOTE
# Atega comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
# Social Links (Footer)
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/simprecicchiani/"}
- {icon: "ion-logo-github", link: "https://github.com/simprecicchiani"}
- {icon: "ion-logo-dribbble", link: "https://www.behance.net/simprecicchiani"}
- {icon: "ion-logo-youtube", link: "https://youtube.com/c/SimonePrecicchiani"}
- {icon: "ion-logo-vimeo", link: "https://vimeo.com/user99934883"}
- {icon: "ion-logo-twitter", link: "https://twitter.com/simprecicchiani"}
- {icon: "ion-logo-facebook", link: "https://www.facebook.com/SimonePrecicchiani/"}
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/simprecicchiani/"}

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Gallery Footer Section
gallery:
  title: Gallery
  images:
    - alt: 'fresco design works'
      url: '/images/padelup-01.jpg'
    - alt: 'fresco design works'
      url: '/images/radio24-05.png'
    - alt: 'fresco design works'
      url: '/images/usc-01.png'
    - alt: 'fresco design works'
      url: '/images/martenzclub-02.png'
    - alt: 'fresco design works'
      url: '/images/martenzclub-04.png'
    - alt: 'fresco design works'
      url: '/images/martenzclub-06.png'

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

# Favicon
favicon:
  source: /images/logo-fdw.png
  path: /images/favicon

sass:
  sass_dir: _sass
  style: compressed
